### ISSUE TITLE
Not able to install vaadin-core

### ISSUE THREAD

**Issue by dayakarmuluka** [vaadin/base-starter-angular#11]
when trying to install `bower vaadin-code`, below exception is thrown
bower                        ENOTFOUND Package vaadin-core not found.

**Comment by web-padawan** [comment]
Hello, could you please do the following steps:

1. Clean cache:
```sh
bower cache clean
```
2. Install it again:
```sh
bower install --save vaadin-core
```

You should see something like this:
```sh
$ bower install --save vaadin-core
bower vaadin-core#*         not-cached https://github.com/vaadin/vaadin-core.git#*
bower vaadin-core#*            resolve https://github.com/vaadin/vaadin-core.git#*
bower vaadin-core#*           download https://github.com/vaadin/vaadin-core/archive/v10.0.2.tar.gz
```
etc, in case your output is different it might be that you have some network issues.

**Comment by dayakarmuluka** [comment]
@web-padawan Still same issue, I was able to install vaadi-core-elements, however vaadin-core is still throwing the error even after clearing bower cache.

**Comment by web-padawan** [comment]
Are you by any chance using any proxy, or corporate network etc?

**Comment by dayakarmuluka** [comment]
I tried with home network,  mobile network and office network.

**Comment by dayakarmuluka** [comment]
in https://bower.io `vaadin-core` and `vaadin-core-elements` both are pointing to same repo https://github.com/vaadin/vaadin-core, do we need to use vaadin-core-elements instead of vaadin-core?

**Comment by web-padawan** [comment]
@dayakarmuluka which version are you using? You should be able to install it like this:

https://github.com/vaadin/expense-manager-demo/blob/321de9a37f46d3f98dae34dd53a127206571bad4/bower.json#L9

`vaadin-core-elements` is the outdated version of this repo which contained older versions of the components. Due to change in our versioning, the latest stable version is now `v10.0.2` and that one should be used to get latest versions.

**Comment by dayakarmuluka** [comment]
@web-padawan I tried with `bower install vaadin/vaadin-core`,  it worked for me.

**Comment by web-padawan** [comment]
Glad you sorted it out. It might be that you had some earlier version of `bower` locally but not sure.
In case if this problem returns, try updating bower to latest version:

```sh
npm i -g bower
```

I will update the README to use the naming which worked for you.
